# Generated by Django 4.2.2 on 2023-06-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_learningvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningvideo',
            old_name='title',
            new_name='translate',
        ),
    ]
