# Generated by Django 4.2.2 on 2023-06-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_social_facebook_profile_social_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_github',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_linkedin',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
